apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keydb.fullname" . }}-utils
  labels:
    {{- include "keydb.labels" . | nindent 4 }}
type: Opaque
stringData:
  server.sh: |
    #!/bin/bash
    keydb-server /etc/keydb/keydb.conf &
    KEYDB_SERVER_PID=$!
    current_replica_number=$(echo $HOSTNAME | grep -oE '[0-9]+$')
    if [[ $current_replica_number -eq $LAST_REPLICA_NUBMER ]];then
      echo -e "\033[0;32mStart initialization keydb-cluster...\e[0m"
      export REDISCLI_AUTH="${REDIS_PASSWORD}"
      nodes=$(echo $REDIS_NODES | tr ' ' '\n')
      for node in $nodes;do
        ip=$(getent hosts $node|awk '{print $1}')
        ips_anonce="$ips_anonce $ip:$REDIS_PORT"
      done
      echo -e "\033[0;32mCLUSER_IPS_ANONCE: $ips_anonce\e[0m"
      echo "yes" | eval keydb-cli --cluster create $ips_anonce --cluster-replicas {{ .Values.keydbConfig.cluster_replicas }}
    fi;
    tail --pid=$KEYDB_SERVER_PID -f /dev/null
